"""user: add last login fields

Revision ID: 6c70172e87c6
Revises: 96f1ab236541
Create Date: 2026-03-08 15:30:42.545047+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c70172e87c6'
down_revision: Union[str, None] = '96f1ab236541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login_device', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_device')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
