"""catalog: update models for products and categories

Revision ID: 2d2cf8f12327
Revises: 91e0755745ef
Create Date: 2026-02-27 18:14:38.258362+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2cf8f12327'
down_revision: Union[str, None] = '91e0755745ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('product_images', sa.Column('alt', sa.String(length=255), server_default='', nullable=False))
    op.add_column('product_images', sa.Column('is_cover', sa.Boolean(), nullable=False))
    op.add_column('product_images', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('product_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('product_images', sa.Column('height', sa.Integer(), nullable=True))
    op.drop_column('product_images', 'is_main')
    op.drop_column('product_images', 'position')
    op.add_column('product_variants', sa.Column('name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('products', sa.Column('description_html', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('meta_title', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('og_image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'og_image_url')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'description_html')
    op.drop_column('product_variants', 'name')
    op.add_column('product_images', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_images', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('product_images', 'height')
    op.drop_column('product_images', 'width')
    op.drop_column('product_images', 'sort_order')
    op.drop_column('product_images', 'is_cover')
    op.drop_column('product_images', 'alt')
    op.drop_column('categories', 'is_active')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
