"""auth: add oauth fields to user

Revision ID: 6a8e3dde9140
Revises: b6883ea3a6b3
Create Date: 2026-03-01 06:36:14.682706+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8e3dde9140'
down_revision: Union[str, None] = 'b6883ea3a6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
