"""Add type to ProductOptionGroup

Revision ID: f6f189d8f825
Revises: 094117ab7638
Create Date: 2026-03-08 17:24:16.974667+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f6f189d8f825'
down_revision: Union[str, None] = '094117ab7638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
