"""add_static_pages

Revision ID: 7e74df555ddc
Revises: 5c40cb47aed7
Create Date: 2026-02-27 11:50:33.104187+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e74df555ddc'
down_revision: Union[str, None] = '5c40cb47aed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_path', sa.String(length=500), nullable=False),
    sa.Column('new_path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_old_path'), 'redirects', ['old_path'], unique=True)
    op.create_table('static_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_pages_is_active'), 'static_pages', ['is_active'], unique=False)
    op.create_index(op.f('ix_static_pages_slug'), 'static_pages', ['slug'], unique=True)
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('blog_post_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog_posts', sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('blog_posts', sa.Column('reading_time_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('blog_posts', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'archived', name='blogstatus', create_type=False),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='blogpoststatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='blogpoststatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'published', 'archived', name='blogstatus', create_type=False),
               existing_nullable=False)
    op.drop_column('blog_posts', 'reading_time_minutes')
    op.drop_column('blog_posts', 'views')
    op.drop_table('blog_post_media')
    op.drop_table('user_notification_settings')
    op.drop_table('notification_logs')
    # ... rest of the file ...
    op.drop_index(op.f('ix_static_pages_slug'), table_name='static_pages')
    op.drop_index(op.f('ix_static_pages_is_active'), table_name='static_pages')
    op.drop_table('static_pages')
    op.drop_index(op.f('ix_redirects_old_path'), table_name='redirects')
    op.drop_table('redirects')
    # ### end Alembic commands ###
