"""Add type to ProductOptionGroup

Revision ID: 094117ab7638
Revises: f3a4b5c6d7e8
Create Date: 2026-03-08 17:23:58.653350+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '094117ab7638'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
