"""test

Revision ID: 64e49a7b83db
Revises: f26f5022506a
Create Date: 2026-03-01 16:18:08.671372+00:00

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64e49a7b83db'
down_revision: Union[str, None] = 'f26f5022506a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_complectations_device_serial_fkey', 'device_complectations', type_='foreignkey')
    op.drop_constraint('module_devices_serial_key', 'module_devices', type_='unique')
    op.create_foreign_key(
        'device_complectations_device_serial_fkey',
        'device_complectations',
        'module_devices',
        ['device_serial'],
        ['serial'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_complectations_device_serial_fkey', 'device_complectations', type_='foreignkey')
    op.create_unique_constraint('module_devices_serial_key', 'module_devices', ['serial'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(
        'device_complectations_device_serial_fkey',
        'device_complectations',
        'module_devices',
        ['device_serial'],
        ['serial'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
