"""blog_rename_reading_time

Revision ID: f26f5022506a
Revises: 20260301_1500
Create Date: 2026-03-01 14:37:24.563050+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26f5022506a'
down_revision: Union[str, None] = '20260301_1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('reading_time', sa.Integer(), nullable=False))
    op.drop_column('blog_posts', 'reading_time_minutes')
    op.drop_constraint('module_devices_serial_key', 'module_devices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('module_devices_serial_key', 'module_devices', ['serial'], postgresql_nulls_not_distinct=False)
    op.add_column('blog_posts', sa.Column('reading_time_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('blog_posts', 'reading_time')
    # ### end Alembic commands ###
