"""products: add content_json

Revision ID: 6ad8390c4ab2
Revises: 64e49a7b83db
Create Date: 2026-03-03 16:00:43.858933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ad8390c4ab2'
down_revision: Union[str, None] = '64e49a7b83db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('products', 'meta_title',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('products', 'meta_description',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'meta_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
    op.alter_column('products', 'meta_title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.drop_column('products', 'content_json')
    # ### end Alembic commands ###
