"""users: add phone and address fields

Revision ID: f07d615f2f2f
Revises: 6a8e3dde9140
Create Date: 2026-03-01 11:05:23.898584+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07d615f2f2f'
down_revision: Union[str, None] = '6a8e3dde9140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_hash')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
